USE [master]
GO

/****** Object:  Database [AdventureWorks2014]    Script Date: 10/3/14 4:05:25 AM ******/
CREATE DATABASE [AdventureWorks2014]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks2014_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\AdventureWorks2014_Data.mdf' , SIZE = 210176KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorks2014_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\AdventureWorks2014_Log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
GO

ALTER DATABASE [AdventureWorks2014] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks2014].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorks2014] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET ANSI_NULLS ON 
GO

ALTER DATABASE [AdventureWorks2014] SET ANSI_PADDING ON 
GO

ALTER DATABASE [AdventureWorks2014] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [AdventureWorks2014] SET ARITHABORT ON 
GO

ALTER DATABASE [AdventureWorks2014] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorks2014] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorks2014] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [AdventureWorks2014] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [AdventureWorks2014] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorks2014] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorks2014] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdventureWorks2014] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorks2014] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorks2014] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorks2014] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorks2014] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdventureWorks2014] SET DELAYED_DURABILITY = DISABLED 
GO

USE [AdventureWorks2014]
GO

EXEC [AdventureWorks2014].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AdventureWorks 2014 Sample OLTP Database' 
GO

USE [master]
GO

ALTER DATABASE [AdventureWorks2014] SET  READ_WRITE 
GO

