USE [master]
GO

/****** Object:  Database [SogetiSkills]    Script Date: 10/2/14 8:19:59 AM ******/
CREATE DATABASE [SogetiSkills]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SogetiSkills', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SogetiSkills.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SogetiSkills_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SogetiSkills_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SogetiSkills] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SogetiSkills].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SogetiSkills] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SogetiSkills] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SogetiSkills] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SogetiSkills] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SogetiSkills] SET ARITHABORT OFF 
GO

ALTER DATABASE [SogetiSkills] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SogetiSkills] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SogetiSkills] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SogetiSkills] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SogetiSkills] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SogetiSkills] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SogetiSkills] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SogetiSkills] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SogetiSkills] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SogetiSkills] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SogetiSkills] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SogetiSkills] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SogetiSkills] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SogetiSkills] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SogetiSkills] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SogetiSkills] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SogetiSkills] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SogetiSkills] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SogetiSkills] SET  MULTI_USER 
GO

ALTER DATABASE [SogetiSkills] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SogetiSkills] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SogetiSkills] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SogetiSkills] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SogetiSkills] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SogetiSkills] SET  READ_WRITE 
GO

